### ISSUE TITLE
Reversion to non-segment averages

### ISSUE THREAD

**Issue by JoshMHardy** [moores-lab/MiRPv2#2]
The reversion to non-segment averages is mixing the rlnImageName's if the star files are not the same length e.g.:
2391.397186	1997.458271	2	90.0	-141.70447	0.0	000025@Extract/job047/Micrographs/**FoilHole_16352013_Data_16352809_16352811_20201017_070254-253085.mrcs**	MotionCorr/job001/Micrographs/**FoilHole_16352014_Data_16352888_16352890_20201017_071014-253100.mrc**	4	3.736792	0.133175	11543.171875	11200.508789	11.080981	0.0	1.0	0.0	-13.84363	-4.58603	482	107.982418	90.04649	-141.70447	1	0.259613	83366.146857	0.985572	10	107.982418

The second star file was shorter since microtubules/segments had been excluded due to the rot angle voting step. 

Also in the manual, the instructions given result in an error message. It expects a star file for -r and I think the input should be the previous step (XY correction star):
generate segment averages -i ./External/mirp pf sorting/14pf data.star -
o ./External/mirp xy correct/ -r Extract/job id/Micrographs
should be:
generate segment averages -i ./External/job id/xyCorrected_data.star -
o ./External/mirp xy correct/ -r ./External/mirp pf sorting/14pf data.star

**Comment by acook2** [comment]
Sorry Josh, I'd managed to sneak an old version of generate_segment_averages.py on there some how... Should be all fixed now, and the manual will now make sense.
